The procedure to generate an ebook from source text gather from web
The source is Project Gutenberg (https://www.gutenberg.org/) as the example to illustrate the procedure.


| Description                          | 1)	Manual                                                                                                                                                                                                                                                                                                                                                                                                                               | 2)	Automatic                                                                                                                                                                                                                                                                                                | Output            |
| ------------------------------------ | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------- |
| Gather source                        | Visit the site https://www.gutenberg.org/ and download files or use browser plugin to download the links in batch.                                                                                                                                                                                                                                                                                                                      | wget -w 2 -m -H http://www.gutenberg.org/robot/harvest?filetypes[]=txt                                                                                                                                                                                                                                      | Txt or epub files |
| Generate book cover                  | Employ 3rd-party tool to select the elements and layout to construct the book cover.Construct the prompt to formulate the key concept of the book and feed the prompt to the AIGC such as DALL-E, Mid Journey, Stable Diffusion, etc.to generate the book cover.Utilize the workflow engine to assembly the functionalities to read the raw text, summarize this text, convert the summary into prompt to feed to text-to-image engine. | Use ebook manipulation library to extract the description of the book, construct the key concept of the book and formulate the prompt from the key concept along with the instruction to draw the book cover of certain style. Use the prompt the generate the graph with certain selection to choose from. | image files       |
| Edit the ebook to add the book cover | Use editing tool such as Calibre-edit tool to add the book cover in epub.                                                                                                                                                                                                                                                                                                                                                               | Write the script to insert the book cover picture into the epub file by using the python library such as * Ebooklib * Python-ebook-builder                                                                                                                                                                  | epub              |
|  Convert the epub to pd format                          | Use Calibre to convert the epub to pdf |  Script pandoc to convert epub into pdf in batch.| pdf | 

